import Head from "next/head";
import React from "react";
import styles from "../../styles/Posts.module.css";

function Posts() {
  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Posts</h1> */}
    </>
  );
}

export default Posts;
