import React from "react";
import Head from "next/head";

function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <div>
        <h1>About</h1>
      </div>
    </>
  );
}

export default About;
