import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Typewriter from "typewriter-effect";
const inter = Inter({ subsets: ["latin"] });
import RabbitSvg from "../public/rabbit.svg";
export default function Home() {
  return (
    <>
      <Head>
        <title>Davy Tao</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <div className={`${styles.center} ${styles.main} ${styles.fade_in}`}>
        <RabbitSvg className={styles.rabbit} />
        <h1>
          <Typewriter
            options={{
              strings: ["Happy Chinese New Year!", "Welcome to my blog"],
              autoStart: true,
              loop: true,
            }}
          />
        </h1>
      </div>
    </>
  );
}
