import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Typewriter from "typewriter-effect";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Davy&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.center} ${styles.main} ${styles.fade_in}`}>
        <h1>
          <Typewriter
            options={{
              strings: [
                "Hi there",
                "Welcome to my blog",
                "This blog is currently under construction",
                "We will meet very soon",
              ],
              autoStart: true,
              loop: true,
            }}
          />
        </h1>
      </div>
    </>
  );
}
