import React from "react";
import { getPublishedTags, getSingleTag } from "../../lib/notion";
import styles from "../../styles/Tag.module.css";
import PostCard from "../../components/PostCard";
import Head from "next/head";

const Tag = ({ posts, tag }: { posts: any[]; tag: string }) => {
  return (
    <>
      <Head>
        <title>{tag}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <h1 className={`${styles.title} ${styles.fade_in}`}>
        Posts tagged with {tag}
      </h1>
      <div className={`${styles.container} ${styles.fade_in}`}>
        {posts.map((post: any, index: any) => (
          <PostCard post={post} key={post.id} />
        ))}
      </div>
    </>
  );
};

export default Tag;
export const getStaticProps = async ({ params }: { params: any }) => {
  const posts = await getSingleTag(params.tag);
  return {
    props: {
      posts,
      tag: params.tag,
    },
    revalidate: 60,
  };
};

export const getStaticPaths = async () => {
  const tags = await getPublishedTags();
  return {
    paths: Object.keys(tags).map((tag) => ({
      params: { tag },
    })),
    fallback: false,
  };
};
