import Head from "next/head";
import React from "react";

function Tags() {
  return (
    <div>
      <Head>
        <title>Tags</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Tags</h1> */}
    </div>
  );
}

export default Tags;
