import Head from "next/head";
import Link from "next/link";
import React from "react";
import { getPublishedTags } from "../../lib/notion";
import styles from "../../styles/Tags.module.css";

function Tags({ tags }: { tags: any }) {
  return (
    <div>
      <Head>
        <title>Tags</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <h1 className={`${styles.title} ${styles.fade_in}`}>All tags</h1>
      <div className={`${styles.container} ${styles.fade_in}`}>
        {Object.keys(tags).map((tag) => (
          <div key={tag}>
            <Link href={`/tags/${tag}`}>
              {tag} ({tags[tag]})
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Tags;

export const getStaticProps = async () => {
  const tags = await getPublishedTags();
  return {
    props: { tags },
    revalidate: 60,
  };
};
